name: Package Size

on:
  pull_request:
  schedule:
    - cron: '0 4 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  package-size-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Dependency sizes
        uses: carlesnunez/check-my-bundlephobia@v1.7.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-dev-dependencies: true
          # threshold: 500
          # strict: true
      - name: Package size report
        uses: pkg-size/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
